shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

catalog:
  '@antfu/eslint-config': ^8.1.1
  '@iconify-json/logos': ^1.2.11
  '@iconify-json/ph': ^1.2.2
  '@node-rs/xxhash': ^1.7.6
  '@nuxt/eslint': ^1.15.2
  '@nuxt/kit': ^4.4.2
  '@sindresorhus/fnv1a': ^3.1.0
  '@unocss/eslint-config': ^66.6.8
  '@unocss/nuxt': ^66.6.8
  eslint: ^10.2.0
  eslint-plugin-format: ^2.0.1
  lightningcss: ^1.32.0
  nuxt: ^4.4.4
  typescript: ^6.0.3
  unocss: ^66.6.8
  vue: ^3.5.32
  vue-router: ^5.0.4
  vue-tsc: ^3.2.6
