catalogMode: strict
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 1440
shamefullyHoist: true
shellEmulator: true

packages:
  - packages/*
  - scripts

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

overrides:
  typescript: npm:typescript-native-bridge@6.0.3-bridge.18.tsgo.7.0.2

catalog:
  '@types/node': ^26.6.4
  npm-run-all2: ^9.0.3
  oxfmt: ^0.72.0
  oxlint: ^1.87.0
  oxlint-tsgolint: ^7.0.2003
  typescript: npm:typescript-native-bridge@6.0.3-bridge.18.tsgo.7.0.2
  vue: ^3.6.0-rc.10
  vue-component-type-helpers: ^3.3.12
  vue-tsc: ^3.3.12

catalogs:
  scripts:
    '@node-rs/xxhash': ^1.7.8
    '@sindresorhus/fnv1a': ^3.1.0
    image-size: ^2.0.4
  website:
    '@iconify-json/logos': ^1.2.15
    '@iconify-json/ph': ^1.2.2
    '@nuxt/kit': ^4.6.0
    '@unocss/nuxt': ^66.10.5
    lightningcss: ^1.33.0
    nuxt: ^4.6.0
    unocss: ^66.10.5
    vue-router: ^5.4.0
