catalogMode: strict
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - fastq@1.20.2

packages:
  - packages/*
  - scripts

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

overrides:
  vite: ^8.0.10

catalog:
  '@antfu/eslint-config': ^9.3.0
  '@nuxt/eslint': ^1.17.0
  '@types/node': ^26.4.0
  '@unocss/eslint-config': ^66.8.1
  eslint: ^10.9.1
  eslint-plugin-format: ^2.0.1
  npm-run-all2: ^9.0.3
  typescript: ^7.0.2
  vue: ^3.5.32
  vue-tsc: ^3.3.11

catalogs:
  scripts:
    '@node-rs/xxhash': ^1.7.6
    '@sindresorhus/fnv1a': ^3.1.0
    image-size: ^2.0.2
  website:
    '@iconify-json/logos': ^1.2.11
    '@iconify-json/ph': ^1.2.2
    '@nuxt/kit': ^4.4.2
    '@unocss/nuxt': ^66.6.8
    lightningcss: ^1.32.0
    nuxt: ^4.5.0
    unocss: ^66.6.8
    vue-router: ^5.0.4
