<script setup lang="ts">
import { GameAbilityId } from '@lolcalc/core/GameAbilityId';
import { gameAbilityImgAttrs } from '@lolcalc/core/misc';
import { AbilityType } from '@lolcalc/shared/index';

const { reportAnIssue } = useReportIssueDialog();

const ambessaRImg = await gameAbilityImgAttrs(GameAbilityId.build(AbilityType.champion, 'Ambessa', 'r', 0));
const nocturneWImg = await gameAbilityImgAttrs(GameAbilityId.build(AbilityType.champion, 'Nocturne', 'w', 0));
</script>

<template>
	<main id="about">
		<h1>about</h1>

		<p>
			For instructions on how to use it, visit the <NuxtLink to="/guide">
				guide page
			</NuxtLink>
		</p>

		<h2>what is it?</h2>
		<p>
			<strong>lolcalc</strong> is intended to be a fully fledged, all-included <a href="https://www.leagueoflegends.com/" target="_blank">League of Legends</a> damage calculator (WIP at the moment). You should be able to choose any champion/item/rune combination and see the same* numbers you will find in game. See the "<a href="#does-it-work">does it work?</a>" section for examples.
		</p>
		<p>*with known discrepancies being</p>
		<ul>
			<li>
				max health and mana/ability resource have a margin of error of <strong>1</strong>. Most of the differences should be coming from floating point arithmetic and the in game ui rounding the displayed value up. This means that the game displays something like <span class="code-like">2773.0000001</span> as <span class="code-like">2774</span>, even though it's effectively <span class="code-like">2773</span> (<a href="#TODO">example config</a>)
			</li>
		</ul>

		<h2 id="does-it-work">
			does it work?
		</h2>
		<p>
			while it's impossible for me to check all 172+ champions with every item combination, I tried my best to make it work and <NuxtLink to="/guide#guide-examples">
				here are some examples
			</NuxtLink> of it working. If you encounter a configuration that's not correctly calculated, please <button class="link-like" @click="reportAnIssue">
				report it
			</button>
		</p>
		<p class="alert info">
			for now only champions, their passives, items (with passives), and rune shards are expected to calculate properly!
			TODO icon
		</p>
		<p>
			non-passive abilities (like <a href="https://wiki.leagueoflegends.com/en-us/Ambessa#Public_Execution" target="_blank"><img v-bind="ambessaRImg" alt="Ambessa R icon"> Ambessa R passive</a> or <a href="https://wiki.leagueoflegends.com/en-us/Nocturne#Shroud_of_Darkness" target="_blank"><img v-bind="nocturneWImg" alt="Nocturne W icon"> Nocturne W passive</a>) and <a href="https://wiki.leagueoflegends.com/en-us/Rune#Rune_paths" target="_blank">rune paths</a> <strong>are not implemented</strong> <i>(yet)</i> in the calculations. See the <NuxtLink to="/guide#test-setup">champion/item/rune setup</NuxtLink> recommended for verifying the calculations yourself
		</p>
		<p>for when these and other features will be implemented, see the <a href="#TODO">roadmap</a></p>

		<h2>acknowledgements</h2>
		<p>This project would not exist without <a href="https://communitydragon.org/" target="_blank">Community Dragon</a> and I want to thank its contributors, as well as people on their discord server that helped me during the development.</p>
		<p>Some of the <strong>code</strong> in this project was generated by/made with the help of LLMs. The <strong>text</strong> on the website is all me, though. Pinky promise. I'd estimate LLM generated code to be less than 10% of the code base, however I do want to say that it would've taken me a few more months to finish without them. The ability to paste it the stats/variables and have it guess formulas for what Riot is doing under the hood was very helpful.</p>
		<p>Thanks to all of my friends who helped me test both the website and the various champion configurations in game.</p>
		<p>Thanks to Riot Games for not chronobreaking this project 🤞</p>
	</main>
</template>

<style>
@layer components {
	#about {
		--at-apply: 'text-lg';

		.code-like {
			--at-apply: 'font-mono bg-slate-900 px-1 py-0.5 -mx-0.5 -my-0.5 rounded-sm';
		}

		a,
		.link-like {
			--at-apply: 'text-blue-400';

			&:hover {
				--at-apply: 'underline';
			}
		}

		img {
			--at-apply: 'inline-block size-5 -translate-y-px';
		}
	}
}
</style>
